# Generated by Django 5.1.1 on 2024-11-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idevelop', '0002_remove_student_following_student_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='friends',
        ),
        migrations.AddField(
            model_name='student',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='idevelop.student'),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
