# Generated by Django 5.1.1 on 2024-11-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idevelop', '0006_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='friends',
        ),
        migrations.AddField(
            model_name='student',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='code_storage',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
