# Generated by Django 4.2.16 on 2024-11-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idevelop', '0002_remove_student_following_student_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='code_storage',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
